config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'home', to: 'welcome#index', as: 'home'

  resources :users

  get 'welcome/index'
  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :first_name,
  			 presence: true

  validates :last_name,
  			 presence: true

  validates :email,
  			 presence: true,

  			 uniqueness: true,


  			format:{
              with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  			}

  def to_s

  	"#{first_name} #{last_name}"

  	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user

  	User.where(id: session[:user_id]).first

  end

  helper_method :current_user
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def login_sucess

  	render :create

  end

  def create

  	user = User.find_by_email(params[:email])

  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		login_sucess
  		
  	else
		render :login_error 
  end

end

  def destroy

  	session[:user_id] = nil
  	redirect_to root_url

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def login
  end

  def register
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div id="user_header" align="center">
	 <% if current_user %>

	 	
	 	Logged in as <%= current_user.email %> 


	 	<% end %>
	</div>
	
	
	<% flash.each do |key, value| %>
	<%= content_tag(:div, class:"alert alert-#{key}") do %>
		<p> <%= value %> </p>

		<% end %>

		<% end %>


<%= yield %>

</body>
</html>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>These are the user(s) who are currently in a database</h1>


<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<head>
<meta name="viewport" content="width=device-width" />

<link rel="stylesheet" type="text/css" href="/~stulacha/poker/app/assets/stylesheets/welcome.scss" />
</head>

<div class ="navbar navbar-inverse navbar-static-top">
    
                            <ul class= "nav navbar-nav navbar-right">
                                                    
                            
                            <li><a href="../login"><strong>Login</strong></a></li>
                            
                        
                          </ul><!-- /.nav -->
</div>

<div class="container">
    <section id="content">
        
            <h1>Register</h1>

 <div><%= render 'form' %></div>


 <div>
     <input type = "checkbox" name = "chkbox" value = "agree" required=""/>&nbspI Agree to the (Privacy Policy)
                                                              
 </div>

</section>

</div>




<footer >
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
           
           <div class="col-md-4" >
           <br>
            <font color="blue">Copyright &copy; 2016 CSC 667 Group # 4 </font>
            </br>
            </div>

            <div class="col-md-8">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    		<%= link_to "Home", home_path %>
                    <!--<a href="../welcome/index">Home</a>-->
                    </li>
                    <li><a data-popup-open="#" href= "#">Terms &amp; Conditions</a></li>
                    <li><a data-popup-open="#" href="#">Privacy Policy</a></li>
                    <li><a data-popup-open="#" href="#">About Us</a></li>
                </ul><!-- /.nav -->
            </div>


        </div>
    </div>
</footer>

app/views/users/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6 ielt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7 ielt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

<link rel="stylesheet" type="text/css" href="poker/app/assets/stylesheets/welcome.scss" />
</head>
<body>

<div class ="navbar navbar-inverse navbar-static-top">
	
	                        <ul class= "nav navbar-nav navbar-right">
                                                    
                            
                            <li><a href="login"><strong>Login</strong></a></li>
                            <li><a href="users/new"><strong>Register</strong></a></li>
                        
                          </ul><!-- /.nav -->
</div>
 <div id="header">
                <div id="header_content">
                    <div class="container">
                        <div class="header_align">
                        <a href="index"><img src="#" id="logo"></a>
                      
                        
                        <!--below here-->
                        

                        
                        </div>
                    </div>
                </div>
            </div>

<footer >
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
           
           <div class="col-md-4" >
           <br>
            <font color="blue">Copyright &copy; 2016 CSC 667 Group # 4 </font>
            </br>
            </div>

            <div class="col-md-8">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                            <%= link_to "Home", home_path %>
                    <!--<a href="#">Home</a>-->

                    </li>
                    <li><a data-popup-open="#" href= "#">Terms &amp; Conditions</a></li>
                    <li><a data-popup-open="#" href="#">Privacy Policy</a></li>
                    <li><a data-popup-open="#" href="#">About Us</a></li>
                </ul><!-- /.nav -->
            </div>


        </div>
    </div>
</footer>



</body>
</html>

app/views/welcome/login.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6 ielt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7 ielt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
<meta name="viewport" content="width=device-width" />

<link rel="stylesheet" type="text/css" href="welcome.scss" />
</head>

<div class ="navbar navbar-inverse navbar-static-top">
	
	                        <ul class= "nav navbar-nav navbar-right">
                                                    
                            
                            <li><a href="login"><strong>Login</strong></a></li>
                            <li><a href="#"><strong>Register</strong></a></li>
                        
                          </ul><!-- /.nav -->
</div>
 <div id="header">
                <div id="header_content">
                    <div class="container">
                        <div class="header_align">
                        <a href="#"><img src="background.jpeg" id="logo"></a>
                      
                        
                        
                        
                        </div>
                    </div>
                </div>
            </div>
<div class="container">
	<section id="content">
		<form action="">
			<h1>Login Form</h1>
			<div>
				<input type="text" placeholder="Username or email" required="" id="username" />
			</div>
			<div>
				<input type="password" placeholder="Password" required="" id="password" />
			</div>
			<div>
				<input type="submit" value="Log in" />
				<a href="#">Lost your password?</a>
				<a href="#">Register</a>
			</div>
		</form><!-- form -->
		
	</section><!-- content -->
</div><!-- container -->



<footer >
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
           
           <div class="col-md-4" >
            <font color="blue">Copyright &copy; 2016 CSC 667 Group # 4 </font>
            </div>

            <div class="col-md-8">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="index">Home</a></li>
                    <li><a data-popup-open="#" href= "#">Terms &amp; Conditions</a></li>
                    <li><a data-popup-open="#" href="#">Privacy Policy</a></li>
                    <li><a data-popup-open="#" href="#">About Us</a></li>
                </ul><!-- /.nav -->
            </div>


        </div>
    </div>
</footer>


</html>

app/views/welcome/register.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6 ielt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7 ielt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
<meta name="viewport" content="width=device-width" />

<link rel="stylesheet" type="text/css" href="/~stulacha/poker/app/assets/stylesheets/welcome.css" />
</head>

<div class ="navbar navbar-inverse navbar-static-top">
    
                            <ul class= "nav navbar-nav navbar-right">
                                                    
                            
                            <li><a href="login.html.erb"><strong>Login</strong></a></li>
                            <li><a href="register.html.erb"><strong>Register</strong></a></li>
                        
                          </ul><!-- /.nav -->
</div>
 <div id="header">
                <div id="header_content">
                    <div class="container">
                        <div class="header_align">
                        <a href="#"><img src="background.jpeg" id="logo"></a>
                      
                        
                        
                        
                        </div>
                    </div>
                </div>
            </div>
            
<div class="container">
    <section id="content">
        <form action="">
            <h1>Register</h1>
            <div>
                <input type="text" placeholder="Username or email" required="" id="username" />
            </div>
            <div>
                <input type="password" placeholder="Password" required="" id="password" />
            </div>
            <div>
                <input type="password" placeholder="Confirm Password" required="" id="password" />
            </div>
            <div>
     <input type = "checkbox" name = "chkbox" value = "agree" required=""/>&nbspI Agree to the (Privacy Policy)
                                                              
                                  
                               </div>
            <div>
                <input type="submit" value="Register" /> 
                
                
            </div>
        </form><!-- form -->
        
    </section><!-- content -->
</div><!-- container -->



<footer >
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
           
           <div class="col-md-4" >
            <font color="blue">Copyright &copy; 2016 CSC 667 Group # 4 </font>
            </div>

            <div class="col-md-8">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="index">Home</a></li>
                    <li><a data-popup-open="#" href= "#">Terms &amp; Conditions</a></li>
                    <li><a data-popup-open="#" href="#">Privacy Policy</a></li>
                    <li><a data-popup-open="#" href="#">About Us</a></li>
                </ul><!-- /.nav -->
            </div>


        </div>
    </div>
</footer>


</html>